on:
  workflow_dispatch:
    inputs:
      version_part:
        description: The part of the version to update (patch, minor or major)
        required: true
        default: 'minor'
jobs:
  prepare-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    env:
      PYTHON_PACKAGE: fake_package
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Bump the version number
      id: bump_version
      run: |
        pip install bump2version
        bump2version minor $PYTHON_PACKAGE/__init__.py
        echo "::set-output name=package_version:$(cat $PYTHON_PACKAGE/__init__.py | grep -Po  '\d\.\d\.\d')"
        echo "${{ steps.bump_version.outputs.package_version }}"
    - name: Update the CHANGELOG according to 'Keep a Changelog'
      uses: thomaseizinger/keep-a-changelog-new-release@v1
      with:
        version: ${{ steps.bump_version.outputs.package_version }}
    - name: Commit and push changes to develop
      run: |
        echo ${{ steps.bump_version.outputs.package_version }}

        
